# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:5.0.25-focal
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ordinals
      # No auth for now
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27018

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379